// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJNh6Vg6xCHJ_5thSdJ-My-WyeXqrI8I',
    appId: '1:934435131428:web:7dbe107f4e70f0984e08b1',
    messagingSenderId: '934435131428',
    projectId: 'kpss-duplicate',
    authDomain: 'kpss-duplicate.firebaseapp.com',
    storageBucket: 'kpss-duplicate.firebasestorage.app',
    measurementId: 'G-KHEMK62LFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9-HV95JJIUVF6tUY-zX75VyTWIc6iJ0',
    appId: '1:934435131428:android:359e87fd54587d144e08b1',
    messagingSenderId: '934435131428',
    projectId: 'kpss-duplicate',
    storageBucket: 'kpss-duplicate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxJtcAZL6cNn9gcj9ka0ix353EwQzjMb4',
    appId: '1:934435131428:ios:caa255110fed711b4e08b1',
    messagingSenderId: '934435131428',
    projectId: 'kpss-duplicate',
    storageBucket: 'kpss-duplicate.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboardTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxJtcAZL6cNn9gcj9ka0ix353EwQzjMb4',
    appId: '1:934435131428:ios:caa255110fed711b4e08b1',
    messagingSenderId: '934435131428',
    projectId: 'kpss-duplicate',
    storageBucket: 'kpss-duplicate.firebasestorage.app',
    iosBundleId: 'com.example.adminDashboardTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJNh6Vg6xCHJ_5thSdJ-My-WyeXqrI8I',
    appId: '1:934435131428:web:d16a0244488984d64e08b1',
    messagingSenderId: '934435131428',
    projectId: 'kpss-duplicate',
    authDomain: 'kpss-duplicate.firebaseapp.com',
    storageBucket: 'kpss-duplicate.firebasestorage.app',
    measurementId: 'G-41VGWQJKV2',
  );
}
